### ISSUE TITLE
Errore in formula risolutiva

### ISSUE THREAD

**Issue by martommi** [beryxz/appunti-analisi-2#1]
https://github.com/beryxz/appunti-analisi-2/blob/0619ed7e2f8580519eedb51ebadaa0cb26474b77/argomenti/equazioni-differenziali/edo-lineari-1-ordine.tex#L423-L430

L'integrale `\int_{{-1}}^{{x}} e^{2\ln(-t)} \frac{1}{t^{2}} \diff t` nella formula risolutiva generale è sbagliato in quanto, come riportato dal problema di cauchy dell'esempio stesso
https://github.com/beryxz/appunti-analisi-2/blob/0619ed7e2f8580519eedb51ebadaa0cb26474b77/argomenti/equazioni-differenziali/edo-lineari-1-ordine.tex#L405
la f(x) dovrebbe essere `\frac{1}{2}` e non `\frac{1}{t^{2}}`, per cui la versione corretta sarebbe:

`\int_{{-1}}^{{x}} e^{2\ln(-t)} \frac{1}{2} \diff t`

**Tutta la risoluzione del problema deve essere adeguata di conseguenza.**

**Comment by beryxz** [comment]
Grazie della correzione. Effettivamente questo esercizio era rimasto sbagliato.

Prima di rilasciare una nuova versione faccio passare 1/2 settimane, così da poterne raggruppare eventuali altri.
