### ISSUE TITLE
Errore di segno in esempio 3 sezione 1.5.7

### ISSUE THREAD

**Issue by martommi** [beryxz/appunti-analisi-2#11]
il segno di `c1` nella seconda espressione del primo sistema è sbagliato. Infatti dovrebbe essere `c1 + c2 - 3 = 1`. Sapendo questo, `c2` diventa `11/2` e il risultato finale diventa `y(x) = e^−x(−3/2 cos(x) + 11/2 sin(x)) + 3/2 x^2 − 3x + 3/2`.

![Screenshot 2024-10-28 172649](https://github.com/user-attachments/assets/7b51a130-f980-458f-bc81-399e7b7ac403)

**Comment by beryxz** [comment]
Grazie della correzione
