### ISSUE TITLE
Esercizio duplicato 2.5.7

### ISSUE THREAD

**Issue by martommi** [beryxz/appunti-analisi-2#13]
Compare un esercizio duplicato. Mi sembra che il primo sia sbagliato, la funzione corretta dovrebbe essere `z = x + 2y`, mentre il secondo sembra corretto.

![Screenshot 2024-11-19 184005](https://github.com/user-attachments/assets/bc888b86-66fe-4d2f-bad5-da76b171464f)

**Comment by beryxz** [comment]
Si, l'esercizio 1 è riferito alla funzione `z = x + 2y`; grazie della correzione

Noto inoltre che nella sezione precedente (2.5.6) il dominio dell'esercizio 1 ha degli errori. Correggo entrambi
