### ISSUE TITLE
Chiarimenti esempio sezione 3.6.3

### ISSUE THREAD

**Issue by martommi** [beryxz/appunti-analisi-2#18]
Suggerisco di mostrare tutto il procedimento quando una volta trovato t, lo si deve considerare all'interno dell'intervallo di esistenza. Per come viene illustrato adesso, potrebbe sembrare che i valori dell'intervallo vengano assegnati a k, quando invece non è così e potrebbe confondere.
![image](https://github.com/user-attachments/assets/5bb7007a-27c0-479f-afc4-cb5678b2dbf1)

**Comment by beryxz** [comment]
@maremorte potresti dare un parere sul fix nella PR collegata?

**Comment by martommi** [comment]
> @maremorte potresti dare un parere sul fix nella PR collegata?

La correzione va bene. Grazie.
