### ISSUE TITLE
Esercizio duplicato 2.5.7

### ISSUE THREAD

**Issue by delu999** [beryxz/appunti-analisi-2#20]
Ho clonato la repo e generato il pdf, qua sembra esserci un esercizio ripetuto
![image](https://github.com/user-attachments/assets/17b21096-1204-401d-843a-44765055c6b7)

**Comment by beryxz** [comment]
Grazie dell'osservazione. Rimuovo l'esercizio 3 in quanto mi sembra del tutto sbagliato.
