### ISSUE TITLE
Notazione sbagliata in 2.2.3

### ISSUE THREAD

**Issue by delu999** [beryxz/appunti-analisi-2#22]
Le componenti 1,2,...,n del vettore x_n dovrebbero essere sottolineate oppure no?

![Screenshot From 2024-12-22 11-53-36](https://github.com/user-attachments/assets/adccdf63-872e-4bf3-8b31-17d5e9d1fcee)

**Comment by beryxz** [comment]
Si, non dovrebbero essere sottolineati, ne li, ne poco sotto.
Come l'ho riscritta ora può andare?

![image](https://github.com/user-attachments/assets/9c4f2b13-076d-4b55-85b9-69b674d04667)

**Comment by delu999** [comment]
Si va bene, grazie
