### ISSUE TITLE
Possibile errore nella definizione di limite

### ISSUE THREAD

**Issue by delu999** [beryxz/appunti-analisi-2#25]
Nel secondo punto non dovrebbe essere d(f(x,y),l)?
Poi non ho ben capito perchè il primo punto è con R^n, mentre il secondo con R^2.

![image](https://github.com/user-attachments/assets/f4a2a6a4-9a87-4eab-99cf-378734fdc312)

**Comment by beryxz** [comment]
@delu999 innanzitutto, grazie ancora per le varie correzioni. Ti rispondo per punti:

> Nel secondo punto non dovrebbe essere d(f(x,y),l)?

Si, questo è un errore da correggere. 
Sempre in questo secondo punto sarebbe anche da esplicitare il fatto che $\underline{x}_0 = (x_0, y_0)$

> Poi non ho ben capito perchè il primo punto è con R^n, mentre il secondo con R^2.

Dovrebbero essere due modi diversi per definire il limite della funzione in più variabili:
- Il primo è quello più generale, con $\underline{x}, \underline{x}_0$ in R^n, usando gli intorni di un punto;
- Il secondo usa la "definizione tramite i delta" però sul caso specifico di R^2.

Non sapendo se la seconda definizione può essere estesa anche a tutto R^n, l'ho lasciata come viene riportata a lezione.

---

Prima di procedere a sistemare, fammi per favore sapere se ti torna o meno il ragionamento e anche se magari hai un'idea su come impostare meglio il tutto così da renderlo più chiaro.

**Comment by delu999** [comment]
Per come presentarlo, per me basta dire questa è la definizione con gli intorni e poi quest'altra è una definizione equivalente (se L è un numero reale) con gli epsilon-delta.

Per generalizzare, sugli appunti di base è scritto in questo modo, e mi sembra essere corretto (manca solamente la barra sopra x_0). Puoi compattare questa in una/due righe e poi sotto scrivere "Per il caso R^2, sarebbe...". Oppure lasci solamente il caso R^2, e scrivi sotto, questa definizione è generalizzabile per R^n
![image](https://github.com/user-attachments/assets/3c28a960-9803-41b1-b53a-8a5087f03cf6)

**Comment by beryxz** [comment]
@delu999  può andare così?

![image](https://github.com/user-attachments/assets/3db1b9ee-492c-473a-928a-8e0d66192bbc)

**Comment by delu999** [comment]
Per me va bene

**Comment by beryxz** [comment]
@delu999 con https://github.com/beryxz/appunti-analisi-2/commit/68ffec210b82cbfa54ddadc61a20184fe295fcff ho aggiunto qualche informazione in più quando si usano epsilon-delta
