### ISSUE TITLE
Possibile piccola precisazione

### ISSUE THREAD

**Issue by delu999** [beryxz/appunti-analisi-2#29]
![image](https://github.com/user-attachments/assets/22efd7c6-246f-47c0-9f86-a1bd48132403)

Credo sia meglio dire che le curve di livello sono le proiezioni sul piano xy delle curve ottenute dall'intersezione del grafico f(x,y) con il piano z=k

Da youmath:
![image](https://github.com/user-attachments/assets/dd5a7357-9327-4ec4-bbb4-d411b4d7b310)

Non apro una nuova issue per questo (testi invece che tesi)
![image](https://github.com/user-attachments/assets/6f4d928f-e6d9-465b-b970-85d5b5063991)

**Comment by beryxz** [comment]
@delu999 che ne dici?

![image](https://github.com/user-attachments/assets/9b8a1b3d-84ac-4dee-b3de-58953463fd36)

**Comment by delu999** [comment]
Ok va bene
