### ISSUE TITLE
Errore in un esercizio della sezione 1.4.11

### ISSUE THREAD

**Issue by delu999** [beryxz/appunti-analisi-2#3]
Forse mi sbaglio, ma nel testo dell'esercizio sembra mancare l'indicazione che si tratta di un problema di Cauchy con la condizione iniziale y(0) = 2. Inoltre, nella soluzione y(x) manca un segno meno. BTW grazie per gli appunti

![Screenshot from 2024-10-07 12-36-15](https://github.com/user-attachments/assets/22ac2728-b589-446b-b2fa-353e2edb4457)

**Comment by beryxz** [comment]
Grazie della correzione; confermo che manca il segno meno.

Si, ci sarebbe anche da rendere più chiaro il testo dell'esercizio.

**Comment by beryxz** [comment]
@delu999 Ho optato per fare le seguenti correzioni

![correzione](https://github.com/user-attachments/assets/36e4cdbf-d498-4c04-8ccb-2e7d907622ab)

Prima di rilasciare una nuova versione faccio passare 1/2 settimane, così da poterne raggruppare eventuali altri.
