### ISSUE TITLE
Chiaramenti per dim disuguaglianza di Cauchy-Schwarz

### ISSUE THREAD

**Issue by delu999** [beryxz/appunti-analisi-2#30]
Forse non è tanto chiaro come si passa da x=-ty a la roba sotto.
Dalla formula in alto <x,y> = ||x||*||y|| sostituisco la x e ottengo <-ty, y> = -t <y,y> = ||x||*||y|| e quindi
dividendo -t = ||x||*||y||/||y||^2, giusto?   

![image](https://github.com/user-attachments/assets/f467f791-7744-456b-a1be-df2321807236)

**Comment by beryxz** [comment]
Si, giusto. È abbastanza immediato però giustamente non costa nulla mettere tutti i passaggi così da renderlo più chiaro.
