### ISSUE TITLE
Precisazione

### ISSUE THREAD

**Issue by delu999** [beryxz/appunti-analisi-2#31]
Credo sia \subseteq, invece di \subset.
P.S. Va bene se ti apro issue per questa roba piccola?
![image](https://github.com/user-attachments/assets/a1445a9d-d784-43fb-a101-ca787b39289a)

**Comment by beryxz** [comment]
@delu999 mi ero perso il P.S.

Certamente, anzi, grazie!
Apri pure tutte le Issue (o PR) che vuoi, anche per piccolezze come questa.
