### ISSUE TITLE
Errore in esercizio 2 sezione 1.4.11 

### ISSUE THREAD

**Issue by martommi** [beryxz/appunti-analisi-2#5]
![Screenshot 2024-10-13 221607](https://github.com/user-attachments/assets/f8e5cb60-7c97-4233-9a84-0128f20a1d14)

Nell'esercizio mostrato al posto di `G(x)` non dovrebbe esserci `G(y)`?

**Comment by beryxz** [comment]
Si, dovrebbe essere $G(y(x))$ al posto di $G(x)$. Inoltre, poco prima direi chè e più appropriato chiamare la $g(y) = 0$ soluzione `singolare` al posto di `stazionaria`.

Ora sistemo, grazie della correzione
