### ISSUE TITLE
Precisazioni in sezioni 2.2.3, 2.2.4 e 2.2.6

### ISSUE THREAD

**Issue by martommi** [beryxz/appunti-analisi-2#7]
![Screenshot 2024-10-16 184613](https://github.com/user-attachments/assets/55180bd3-63d8-493c-9506-aaa7b4e4be79)
_Proposizione 3, sezione 2.2.3_: suggerisco di riformulare la definizione di unicità come segue `Se <la successione> ammette limite, allora questo è unico.` , rimuovendo la parte iniziale `[...] ha massimo un limite`. Credo sia più chiaro.

![Screenshot 2024-10-16 185245](https://github.com/user-attachments/assets/dae28bee-243d-4c04-9c8c-03011f38c0a3)
_Esempi, sezione 2.2.4_: suggerisco di aggiungere alcuni disegni per maggiore chiarezza, li allego di seguito.
[Cerchio](https://files.catbox.moe/4zo6d8.png) [Rombo](https://files.catbox.moe/dgz490.png)

![Screenshot 2024-10-16 185612](https://github.com/user-attachments/assets/8e5e9205-36a6-48fd-b0ff-c1d8ea0267b1)
_Esempio, sezione 2.2.6_: suggerisco di aggiungere alcuni disegni per maggiore chiarezza, li allego di seguito.
[Esempio1](https://files.catbox.moe/tyyf0w.png) [Esempio2](https://files.catbox.moe/igfdjv.png) [Esempio3](https://files.catbox.moe/x9wqgd.png)

In generale nella sezione 2.2.6, la frontiera viene descritta dalla notazione `dA`. Suggerisco di modificare in `<delta>A` in quanto `dA` non è una notazione solitamente usata per indicare la frontiera e potrebbe generare confusione.

**Comment by martommi** [comment]
Ho invertito il titolo del disegno delll'esempio 1 con quello dell'esempio 2.
Inoltre mi sono reso conto che il mio disegno dell'esempio 2 (A2 sul  foglio) considera che ci sia un 9 al posto del 25.

**Comment by beryxz** [comment]
Grazie dei feedback, ti rispondo a tutte separatamente

---

> Proposizione 3, sezione 2.2.3: suggerisco di riformulare la definizione di unicità come segue Se <la successione> ammette limite, allora questo è unico. , rimuovendo la parte iniziale [...] ha massimo un limite. Credo sia più chiaro.

Concordo, la parte iniziale è irrilevante, questa la tolgo subito.

> Esempi, sezione 2.2.4: suggerisco di aggiungere alcuni disegni per maggiore chiarezza, li allego di seguito.

Si potrebbe anche riportare nuovamente che con `d` si intende la distanza Euclidea e che con `d_1` si intende la distanza Taxicab.

Le immagini non sarebbero male, riesci per caso ad aggiustarle un attimo cosicchè siano pronte per essere inserite direttamente? Nelle immagini direi che andrebbe sistemato:
- rimuovere `x1=` e `x2=` nelle legende.
- rimuovere o rendere più chiaro il titolo in alto, ad esempio con: "CERCHIO" -> "_B_(<ins>0</ins>, 1) con distanza Euclidea"
- rimuovere i numeri singoli (1,-1) intorno all'imaggine, o sostituirli con le rispettive coordinate complete.

> Esempio, sezione 2.2.6: suggerisco di aggiungere alcuni disegni per maggiore chiarezza, li allego di seguito.

Anche qui le immagini sarebbero utili. Riesci anche in questo caso ad aggiustare gli stessi problemi elencati sopra?
Usando come titoli, nulla, oppure il testo `Esempio A1`, `Esempio A2`, `Esempio A3`

> In generale nella sezione 2.2.6, la frontiera viene descritta dalla notazione dA. Suggerisco di modificare in <delta>A in quanto dA non è una notazione solitamente usata per indicare la frontiera e potrebbe generare confusione.

In effetti sembra che la notazione più usata sia $\partial A$, questo lo aggiusto subito.

**Comment by martommi** [comment]
> Si potrebbe anche riportare nuovamente che con d si intende la distanza Euclidea e che con d_1 si intende la distanza Taxicab.

Sono d'accordo.

Si, appena riesco sistemo le immagini come dici e le ricarico.

**Comment by martommi** [comment]
Ecco le immagini, fammi pure sapere se c'è ancora qualcosa da sistemare.

[Cerchio](https://ibb.co/b7qGJJJ) 
[Rombo](https://ibb.co/L91ZnBG) 
[A3](https://ibb.co/6W8Rcky) 
[A2](https://ibb.co/PQg1Z4H) 
[A1](https://ibb.co/CzxHF6K)

**Comment by beryxz** [comment]
I valori degli assi non mi dispiacevano, erano le legende degli assi, `x1=x` e `x2=y`, che erano poco chiare.

Per il resto ti chiederei di sistemare un'ultima cosa. Ci sarebbe da uniformare le linee rosse rappresentanti le funzioni, usando il tratteggiato quando i punti non sono inclusi e usando la linea piena quando i punti sono inclusi.

Al momento solo nell'immagine di `A2` hai messo tratteggiata la funzione, ci sarebbe però da farlo anche per `Cerchio`, `Rombo` e `A1` se non erro.

**Comment by martommi** [comment]
Ho aggiornato il mio commento precedente con le immagini.

**Comment by beryxz** [comment]
Grazie!

Ho aggiunto tutto nella #10
